"""CSS emitter: header, sorted output, precision, defaults, determinism."""

import re

from typogr import emit


def test_css_header_and_sorted(known_scale):
    text = emit.css(known_scale, "t-shirt")
    lines = text.splitlines()
    assert lines[0] == "/* generated by typogr 1.0.0 */"
    assert lines[1] == ":root {"
    assert lines[-1] == "}"
    body = lines[2:-1]
    assert body == sorted(body)
    assert all(line.startswith("    --") for line in body)


def test_css_precision_px_two_rem_four(known_scale):
    text = emit.css(known_scale, "t-shirt")
    px_values = re.findall(r"^\s+--[\w-]+: ([\d.]+)px;", text, re.M)
    assert px_values, "no px declarations found"
    for value in px_values:
        assert re.fullmatch(r"\d+\.\d{2}", value), value
    assert "--text-lg: 20.00px;" in text
    assert "--text-2xl: 31.25px;" in text
    # rows carry the exact dp contract
    for row in known_scale:
        assert re.fullmatch(r"\d+\.\d{2}", "%.2f" % row["px"])
        assert re.fullmatch(r"\d+\.\d{4}", "%.4f" % row["rem"])


def test_css_line_height_defaults(known_scale):
    text = emit.css(known_scale, "t-shirt")
    # 31.25px step (>= 24 px) gets the heading treatment; 16px step the body one
    assert "--text-2xl-line-height: 1.15;" in text
    assert "--text-2xl-letter-spacing: -0.02em;" in text
    assert "--text-base-line-height: 1.65;" in text
    assert "--text-base-letter-spacing: 0em;" in text


def test_css_extra_overrides(known_scale):
    text = emit.css(
        known_scale,
        "t-shirt",
        {
            "line_heights": {"headings": 1.1, "body": 1.4},
            "letter_spacing": {"tight": -0.01, "default": 0.0},
        },
    )
    assert "--text-2xl-line-height: 1.10;" in text
    assert "--text-2xl-letter-spacing: -0.01em;" in text
    assert "--text-base-line-height: 1.40;" in text


def test_css_deterministic(known_scale):
    a = emit.css(known_scale, "t-shirt")
    b = emit.css(known_scale, "t-shirt")
    assert a == b
    assert a.endswith("}\n")


def test_table_columns(known_scale):
    text = emit.table(known_scale)
    lines = text.splitlines()
    assert lines[0].split() == ["step", "token", "px", "rem"]
    assert len(lines) == 11  # header + rule + 9 rows
    assert "--text-base" in lines[4]
    assert "16.00" in lines[4]
    assert "1.0000" in lines[4]
    assert a_table_deterministic(known_scale)


def a_table_deterministic(known_scale):
    return emit.table(known_scale) == emit.table(known_scale)
