"""Output formatting: CSS custom properties and a plain text table.

Everything here is a pure string function of its inputs - the same rows
always produce the same bytes.
"""

from typogr import __version__


def _fmt_px(px):
    return "%.2fpx" % px


def _fmt_unitless(value):
    return "%.2f" % value


def _fmt_em(value):
    if value == 0:
        return "0em"
    return "%gem" % value


def css(scale_rows, naming, extra=None):
    """Emit ``:root { --token: value; }`` custom properties.

    Per step: the token itself in px, plus ``<token>-line-height`` and
    ``<token>-letter-spacing``. Defaults (override via ``extra``):
      line-heights   1.15 for steps >= 24 px (headings), 1.65 below (body)
      letter-spacing -0.02em for steps >= 24 px, 0em below

    ``extra`` shape::

        {"line_heights": {"headings": 1.15, "body": 1.65},
         "letter_spacing": {"tight": -0.02, "default": 0.0}}

    Declarations are sorted (token, then kind) so output is byte-stable.
    The ``naming`` argument is accepted for API compatibility; the rows
    already carry their token names.
    """
    extra = extra or {}
    lh_cfg = extra.get("line_heights", {}) or {}
    ls_cfg = extra.get("letter_spacing", {}) or {}
    lh_headings = float(lh_cfg.get("headings", 1.15))
    lh_body = float(lh_cfg.get("body", 1.65))
    ls_tight = float(ls_cfg.get("tight", -0.02))
    ls_none = float(ls_cfg.get("default", 0.0))

    decls = []
    for row in scale_rows:
        token = row["name"]
        heading = float(row["px"]) >= 24.0
        line_height = lh_headings if heading else lh_body
        letter_spacing = ls_tight if heading else ls_none
        decls.append("%s: %s;" % (token, _fmt_px(row["px"])))
        decls.append("%s-line-height: %s;" % (token, _fmt_unitless(line_height)))
        decls.append("%s-letter-spacing: %s;" % (token, _fmt_em(letter_spacing)))
    decls.sort()

    lines = ["/* generated by typogr %s */" % __version__, ":root {"]
    lines.extend("    %s" % d for d in decls)
    lines.append("}")
    return "\n".join(lines) + "\n"


def table(scale_rows):
    """A plain token table: step | token | px | rem.

    Copy-paste friendly; the live Aa preview belongs to the specimen.
    """
    token_w = max([len(row["name"]) for row in scale_rows] + [len("token")])
    lines = [
        "%5s  %-*s  %8s  %9s" % ("step", token_w, "token", "px", "rem"),
        "%5s  %-*s  %8s  %9s" % ("-" * 4, token_w, "-" * token_w, "-" * 8, "-" * 9),
    ]
    for row in scale_rows:
        lines.append(
            "%5d  %-*s  %8.2f  %9.4f"
            % (row["step"], token_w, row["name"], row["px"], row["rem"])
        )
    return "\n".join(lines) + "\n"
